### ISSUE TITLE
works out of the box, minor glitch, but I get an error message on every questions I try

### ISSUE THREAD

**Issue by Pumpapa** [ushakrishnan/SearchWithOpenAI#1]
First: thanks for sharing this. It works out of the box, so many kudos's.  (well, almost, gcc5 doesn't work on Ubuntu 22.04, old gcc also works :-)

Whenever I ask a question I get the error message below, which I don't understand. If the phrasing of the question is indeed the issue, I'm not sure how it should be phrased.

So, I don't know if this is an issue or just my ignorance.

> st.warningmethodstreamlit.delta_generator.AlertMixin.warning(body: 'SupportsStr', *, icon: Optional[str] = None) -> 'DeltaGenerator'
> Display warning message.
> 
> Parameters
> ----------
> body : str
>     The warning text to display.
> icon : str or None
>     An optional, keyword-only argument that specifies an emoji to use as
>     the icon for the alert. Shortcodes are not allowed, please use a
>     single character instead. E.g. "🚨", "🔥", "🤖", etc.
>     Defaults to None, which means no icon is displayed.
> 
> Example
> -------
> >>> import streamlit as st
> >>>
> >>> st.warning('This is a warning', icon="⚠️")
> 
> That was a difficult question! I could choked on it!! Can you please try again with rephrasing it a bit?
> 
> Tokens Used: 0 Prompt Tokens: 0 Completion Tokens: 0 Successful Requests: 0 Total Cost (USD): $0.0
> 
> This information was found in:

**Comment by ushakrishnan** [comment]
Hello  @Pumpapa, Glad it has been helpful to you.  Thank you for providing the details.  Did you start getting this error after you invoked / opened Azure OpenAI?   Azure OpenAI routines (on LangChain) has some shared variables with OpenAi, and need to debug to resolve conflicts.  Also, good input on error not being appropriate, will do the right thing.

Can you try restarting the app, and indexing and then trying OpenAI with a few prompts without opening Azure OpenAI?  I guess that should work with no issues.

If the above is not the routine you did, and still getting errors, please send the sequence of what you did, and we can debug to see what your issue is.

Working on fixing Azure OpenAI and will let you know when I post the updated code.

**Comment by ushakrishnan** [comment]
Also, good input on the error.  I will be more clear in providing response error.

**Comment by Pumpapa** [comment]
Hey @ushakrishnan,
thanks for looking into this.
I didn't configure Azure OpenAI (don't use Azure).
Restarted and tried again, same result:
- st.warning, ...
- "that was a difficult question ..."
- 0 tokens used and other stats,
- but four relevant snippets from the docs

**Comment by ushakrishnan** [comment]
In file - 6_Q&A_with_OpenAI.py find the following code and replace it as suggested.  You will get detailed error in command window.  Can you share that?

Code to change:
```
        except:
            st.warning
            st.write("That was a difficult question!  I could choked on it!!  Can you please try again with rephrasing it a bit?")
            st.write(cb)
```

Code to change to
```
        except Exception as e:
            st.warning
            st.write("That was a difficult question!  I could choked on it!!  Can you please try again with rephrasing it a bit?")
            st.write(cb)
            print(e)
```
print(e) will provide detailed error in command / terminal.

**Comment by Pumpapa** [comment]
I'm confused. I did as you suggested. [The log is here](https://filedn.com/lal21yEo6S7F2GrxxR6JoSJ/log).
But: I saw in the log snippets of a trial yesterday, even though I did "CleanUpChromaDB" and restarted the app. 
For good measure I then emptied the entire db directory but I still see yesterday's stuff. I don't know where that persists. All queries result in the same error message as before.
Emptying .../db/ resulted in some additional errors:

```
Could not import azure.core python package.
Using embedded DuckDB with persistence: data will be stored in: db/
Using embedded DuckDB with persistence: data will be stored in: db/
2023-05-26 11:24:23.283 Uncaught app exception
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/pum/Bork/Projects/SearchWithOpenAI/pages/6_Q&A_with_Open_AI.py", line 74, in <module>
    search = store.similarity_search_with_score(prompt)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/langchain/vectorstores/chroma.py", line 229, in similarity_search_with_score
    results = self.__query_collection(
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/langchain/utils.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/langchain/vectorstores/chroma.py", line 121, in __query_collection
    return self._collection.query(
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/chromadb/api/models/Collection.py", line 227, in query
    return self._client._query(
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/chromadb/api/local.py", line 437, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/chromadb/db/clickhouse.py", line 585, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/chromadb/db/index/hnswlib.py", line 240, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying
Using embedded DuckDB with persistence: data will be stored in: db/
Using embedded DuckDB with persistence: data will be stored in: db/
Using embedded DuckDB with persistence: data will be stored in: db/
Using embedded DuckDB with persistence: data will be stored in: db/
```

**Comment by Pumpapa** [comment]
While working on this I commented out all azure-related stuff in .env. That seemed to do the trick. 
No error message and a sensible response.

Thanks again for looking into this, though.

.env:
```
# Set this to `azure`
## OPENAI_API_TYPE="azure"
# The API version you want to use: set this to `2022-12-01` for the released version.
OPENAI_API_VERSION="2022-12-01"
# The base URL for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource.
##OPENAI_API_BASE="https://your-resource-name.openai.azure.com"
# The API key for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource.
##AZ_OPENAI_API_KEY="<your Azure OpenAI API key>"

OPENAI_API_KEY="sk-<my API key>"
TOKENIZE
```

**Comment by ushakrishnan** [comment]
Thank you very much @Pumpapa for sharing how you resolved it.  In a more recent update, I have changed the names of Azure env values to remove the conflict.  Thanks for pointing that out.
