### ISSUE TITLE
IndexError: list index out of range when no .txt files

### ISSUE THREAD

**Issue by Pumpapa** [ushakrishnan/SearchWithOpenAI#4]
Small glitch: if there are no .txt files in `sou` an error is generated `IndexError: list index out of range`
I tested this. There has to be a .txt file, and it must contain at least one line of printable text.

**Comment by ushakrishnan** [comment]
> Small glitch: if there are no .txt files in `sou` an error is generated `IndexError: list index out of range`
> 
> I tested this. There has to be a .txt file, and it must contain at least one line of printable text.

Yeah, good one. Bug!  Will fix.
